from types import ModuleType

class Connection:
    @property
    def root(self) -> ServiceRoot: ...
    def close(self) -> None: ...

class ServiceRoot:
    def getmodule(self, name: str) -> ModuleType: ...
    def health_check(self) -> dict[str, bool | int | str | None]: ...

class Service:
    def on_connect(self, conn: Connection) -> None: ...
    def on_disconnect(self, conn: Connection) -> None: ...

class SlaveService(Service): ...

def connect(
    host: str,
    port: int,
    service: type[Service] | None = None,
    config: dict[str, object] | None = None,
) -> Connection: ...
