"""Entry point for mt5linux.

Usage (Wine mode - for mt5docker):
    python -m mt5linux python.exe                              # Start via Wine
    python -m mt5linux python.exe -p 8001 -w wine64            # Custom port/wine
    python -m mt5linux --host 0.0.0.0 -p 8001 -w wine python.exe  # Options first

Usage (Server mode - direct):
    python -m mt5linux server --host 0.0.0.0 --port 18812
"""

from __future__ import annotations

import sys
from pathlib import Path
from subprocess import Popen

from mt5linux.server import run_server

DEFAULT_HOST = "0.0.0.0"  # noqa: S104
DEFAULT_PORT = 18812


def _generate_server_script(filepath: str) -> None:
    """Generate classic RPyC server script.

    This script will run inside Wine with Windows Python.
    """
    code = r'''#!/usr/bin/env python
"""Classic RPyC server running SlaveService.

Generated by mt5linux for execution inside Wine.
"""
import argparse
from rpyc.utils.server import ThreadedServer
from rpyc.core import SlaveService

def main():
    parser = argparse.ArgumentParser(description="RPyC Classic Server")
    parser.add_argument("--host", default="0.0.0.0", help="Host to bind")
    parser.add_argument("-p", "--port", type=int, default=18812, help="Port")
    args = parser.parse_args()

    print(f"[mt5linux] Starting RPyC server on {args.host}:{args.port}")
    server = ThreadedServer(
        SlaveService,
        hostname=args.host,
        port=args.port,
        reuse_addr=True,
    )
    try:
        server.start()
    except KeyboardInterrupt:
        print("[mt5linux] Server stopped")

if __name__ == "__main__":
    main()
'''
    Path(filepath).write_text(code)


def run_wine_server(
    python_exe: str,
    host: str = DEFAULT_HOST,
    port: int = DEFAULT_PORT,
    wine_cmd: str = "wine",
    server_dir: str = "/tmp/mt5linux",  # noqa: S108
) -> int:
    """Start RPyC server via Wine.

    Args:
        python_exe: Path to Windows Python executable.
        host: Host to bind to.
        port: Port to listen on.
        wine_cmd: Wine command (wine, wine64, etc).
        server_dir: Directory to store generated server script.

    Returns:
        Exit code from Wine process.
    """
    Path(server_dir).mkdir(parents=True, exist_ok=True)

    server_script = str(Path(server_dir) / "server.py")
    _generate_server_script(server_script)

    print(f"[mt5linux] Starting server via {wine_cmd}")
    print(f"[mt5linux] Python: {python_exe}")
    print(f"[mt5linux] Host: {host}, Port: {port}")

    process = Popen(
        [wine_cmd, python_exe, server_script, "--host", host, "-p", str(port)],
    )
    return process.wait()


def run_direct_server(host: str = DEFAULT_HOST, port: int = DEFAULT_PORT) -> int:
    """Run RPyC server directly (without Wine).

    Args:
        host: Host to bind to.
        port: Port to listen on.

    Returns:
        Exit code.
    """

    run_server(host=host, port=port)
    return 0


def _parse_wine_mode_args(argv: list[str]) -> dict[str, str | int]:
    """Parse arguments for Wine mode (manual parsing to avoid argparse conflicts).

    Supports both orderings:
        python -m mt5linux python.exe -p 8001 -w wine
        python -m mt5linux --host 0.0.0.0 -p 8001 -w wine python.exe
    """
    result: dict[str, str | int] = {
        "host": DEFAULT_HOST,
        "port": DEFAULT_PORT,
        "wine": "wine",
        "server_dir": "/tmp/mt5linux",  # noqa: S108
        "python_exe": "",
    }

    i = 0
    while i < len(argv):
        arg = argv[i]

        if arg in ("--host",):
            if i + 1 < len(argv):
                result["host"] = argv[i + 1]
                i += 2
                continue
        elif arg in ("-p", "--port"):
            if i + 1 < len(argv):
                result["port"] = int(argv[i + 1])
                i += 2
                continue
        elif arg in ("-w", "--wine"):
            if i + 1 < len(argv):
                result["wine"] = argv[i + 1]
                i += 2
                continue
        elif arg in ("-s", "--server-dir"):
            if i + 1 < len(argv):
                result["server_dir"] = argv[i + 1]
                i += 2
                continue
        elif not arg.startswith("-"):
            # Positional argument - python.exe path
            result["python_exe"] = arg
            i += 1
            continue

        i += 1

    return result


def _parse_server_mode_args(argv: list[str]) -> dict[str, str | int]:
    """Parse arguments for direct server mode."""
    result: dict[str, str | int] = {
        "host": DEFAULT_HOST,
        "port": DEFAULT_PORT,
    }

    i = 0
    while i < len(argv):
        arg = argv[i]

        if arg in ("--host",):
            if i + 1 < len(argv):
                result["host"] = argv[i + 1]
                i += 2
                continue
        elif arg in ("--port",) and i + 1 < len(argv):
            result["port"] = int(argv[i + 1])
            i += 2
            continue

        i += 1

    return result


def _print_help() -> None:
    """Print usage help."""
    print("""mt5linux - MetaTrader5 bridge for Linux

Usage:
  Wine mode (for mt5docker - runs RPyC server inside Wine):
    python -m mt5linux python.exe
    python -m mt5linux python.exe -p 8001 -w wine64
    python -m mt5linux --host 0.0.0.0 -p 8001 -w wine python.exe

  Direct server mode (runs RPyC server on Linux):
    python -m mt5linux server --host 0.0.0.0 --port 18812

Options (Wine mode):
  --host HOST       Host to bind (default: 0.0.0.0)
  -p, --port PORT   Port to listen on (default: 18812)
  -w, --wine CMD    Wine command (default: wine)
  -s, --server-dir  Directory for generated server script

Options (server mode):
  --host HOST       Host to bind (default: 0.0.0.0)
  --port PORT       Port to listen on (default: 18812)
""")


def main() -> int:
    """Entry point."""
    argv = sys.argv[1:]

    # No arguments - print help
    if not argv:
        _print_help()
        return 1

    # Check for help flag
    if "-h" in argv or "--help" in argv:
        _print_help()
        return 0

    # Direct server mode: python -m mt5linux server [options]
    if argv[0] == "server":
        args = _parse_server_mode_args(argv[1:])
        return run_direct_server(
            host=str(args["host"]),
            port=int(args["port"]),
        )

    # Wine mode: python -m mt5linux [options] python.exe
    args = _parse_wine_mode_args(argv)

    if not args["python_exe"]:
        print("Error: python.exe path required for Wine mode")
        print("Use 'python -m mt5linux server' for direct mode")
        _print_help()
        return 1

    return run_wine_server(
        python_exe=str(args["python_exe"]),
        host=str(args["host"]),
        port=int(args["port"]),
        wine_cmd=str(args["wine"]),
        server_dir=str(args["server_dir"]),
    )


if __name__ == "__main__":
    sys.exit(main())
