"""Entry point for mt5linux.

Usage (Wine mode - for mt5docker):
    python -m mt5linux python.exe                    # Start via Wine
    python -m mt5linux python.exe -p 8001            # Custom port
    python -m mt5linux python.exe -w wine64          # Custom wine command

Usage (Server mode - direct):
    python -m mt5linux server --host 0.0.0.0 --port 18812
"""

from __future__ import annotations

import argparse
import os
import sys
from subprocess import Popen

from mt5linux.server import run_server

DEFAULT_HOST = "0.0.0.0"  # noqa: S104
DEFAULT_PORT = 18812


def _generate_server_script(filepath: str) -> None:
    """Generate classic RPyC server script.

    This script will run inside Wine with Windows Python.
    """
    code = r'''#!/usr/bin/env python
"""Classic RPyC server running SlaveService.

Generated by mt5linux for execution inside Wine.
"""
import argparse
from rpyc.utils.server import ThreadedServer
from rpyc.core import SlaveService

def main():
    parser = argparse.ArgumentParser(description="RPyC Classic Server")
    parser.add_argument("--host", default="0.0.0.0", help="Host to bind")
    parser.add_argument("-p", "--port", type=int, default=18812, help="Port")
    args = parser.parse_args()

    print(f"[mt5linux] Starting RPyC server on {args.host}:{args.port}")
    server = ThreadedServer(
        SlaveService,
        hostname=args.host,
        port=args.port,
        reuse_addr=True,
    )
    try:
        server.start()
    except KeyboardInterrupt:
        print("[mt5linux] Server stopped")

if __name__ == "__main__":
    main()
'''
    with open(filepath, "w") as f:
        f.write(code)


def run_wine_server(
    python_exe: str,
    host: str = DEFAULT_HOST,
    port: int = DEFAULT_PORT,
    wine_cmd: str = "wine",
    server_dir: str = "/tmp/mt5linux",  # noqa: S108
) -> int:
    """Start RPyC server via Wine.

    Args:
        python_exe: Path to Windows Python executable.
        host: Host to bind to.
        port: Port to listen on.
        wine_cmd: Wine command (wine, wine64, etc).
        server_dir: Directory to store generated server script.

    Returns:
        Exit code from Wine process.
    """
    os.makedirs(server_dir, exist_ok=True)

    server_script = os.path.join(server_dir, "server.py")
    _generate_server_script(server_script)

    print(f"[mt5linux] Starting server via {wine_cmd}")
    print(f"[mt5linux] Python: {python_exe}")
    print(f"[mt5linux] Host: {host}, Port: {port}")

    process = Popen(
        [wine_cmd, python_exe, server_script, "--host", host, "-p", str(port)],
    )
    return process.wait()


def run_direct_server(host: str = DEFAULT_HOST, port: int = DEFAULT_PORT) -> int:
    """Run RPyC server directly (without Wine).

    Args:
        host: Host to bind to.
        port: Port to listen on.

    Returns:
        Exit code.
    """

    run_server(host=host, port=port)
    return 0


def main() -> int:
    """Entry point."""
    parser = argparse.ArgumentParser(
        description="mt5linux - MetaTrader5 bridge for Linux",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Wine mode (for mt5docker):
  python -m mt5linux python.exe
  python -m mt5linux python.exe -p 8001 -w wine64

  # Direct server mode:
  python -m mt5linux server --host 0.0.0.0 --port 18812
""",
    )

    subparsers = parser.add_subparsers(dest="command", help="Command")

    # Server subcommand (direct mode)
    server_parser = subparsers.add_parser(
        "server",
        help="Start RPyC server directly (without Wine)",
    )
    server_parser.add_argument("--host", default=DEFAULT_HOST, help="Host to bind")
    server_parser.add_argument("--port", type=int, default=DEFAULT_PORT, help="Port")

    # Wine mode arguments
    parser.add_argument(
        "python_exe",
        nargs="?",
        help="Windows Python executable path (for Wine mode)",
    )
    parser.add_argument(
        "--host",
        default=DEFAULT_HOST,
        help="Host to bind (default: 0.0.0.0)",
    )
    parser.add_argument(
        "-p", "--port",
        type=int,
        default=DEFAULT_PORT,
        help="Port to listen on (default: 18812)",
    )
    parser.add_argument(
        "-w", "--wine",
        default="wine",
        help="Wine command (default: wine)",
    )
    parser.add_argument(
        "-s", "--server-dir",
        default="/tmp/mt5linux",  # noqa: S108
        help="Directory for generated server script",
    )

    args = parser.parse_args()

    # Handle 'server' subcommand
    if args.command == "server":
        return run_direct_server(host=args.host, port=args.port)

    # Handle Wine mode (python.exe as positional argument)
    if args.python_exe:
        return run_wine_server(
            python_exe=args.python_exe,
            host=args.host,
            port=args.port,
            wine_cmd=args.wine,
            server_dir=args.server_dir,
        )

    parser.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
