"""MT5 enums auto-generated from MetaTrader5 library.

DO NOT EDIT THIS FILE MANUALLY!
Generated: 2025-12-14T20:24:08.145943+00:00
Source: mt5docker (rpyc:8001)

To regenerate:
    python scripts/codegen_enums.py
"""

from enum import IntEnum

__all__ = [
    "AccountMarginMode",
    "AccountStopoutMode",
    "AccountTradeMode",
    "BookType",
    "CopyTicksFlag",
    "DayOfWeek",
    "DealEntry",
    "DealReason",
    "DealType",
    "OrderFilling",
    "OrderReason",
    "OrderState",
    "OrderTime",
    "OrderType",
    "PositionReason",
    "PositionType",
    "SymbolCalcMode",
    "SymbolChartMode",
    "SymbolOptionMode",
    "SymbolOptionRight",
    "SymbolSwapMode",
    "SymbolTradeExecution",
    "SymbolTradeMode",
    "TickFlag",
    "TimeFrame",
    "TradeAction",
    "TradeRetcode",
]


class AccountMarginMode(IntEnum):
    """MT5 AccountMarginMode constants."""

    RETAIL_NETTING = 0
    EXCHANGE = 1
    RETAIL_HEDGING = 2


class AccountStopoutMode(IntEnum):
    """MT5 AccountStopoutMode constants."""

    PERCENT = 0
    MONEY = 1


class AccountTradeMode(IntEnum):
    """MT5 AccountTradeMode constants."""

    DEMO = 0
    CONTEST = 1
    REAL = 2


class BookType(IntEnum):
    """MT5 BookType constants."""

    SELL = 1
    BUY = 2
    SELL_MARKET = 3
    BUY_MARKET = 4


class CopyTicksFlag(IntEnum):
    """MT5 CopyTicksFlag constants."""

    ALL = -1
    INFO = 1
    TRADE = 2


class DayOfWeek(IntEnum):
    """MT5 DayOfWeek constants."""

    SUNDAY = 0
    MONDAY = 1
    TUESDAY = 2
    WEDNESDAY = 3
    THURSDAY = 4
    FRIDAY = 5
    SATURDAY = 6


class DealEntry(IntEnum):
    """MT5 DealEntry constants."""

    IN = 0
    OUT = 1
    INOUT = 2
    OUT_BY = 3


class DealReason(IntEnum):
    """MT5 DealReason constants."""

    CLIENT = 0
    MOBILE = 1
    WEB = 2
    EXPERT = 3
    SL = 4
    TP = 5
    SO = 6
    ROLLOVER = 7
    VMARGIN = 8
    SPLIT = 9


class DealType(IntEnum):
    """MT5 DealType constants."""

    BUY = 0
    SELL = 1
    BALANCE = 2
    CREDIT = 3
    CHARGE = 4
    CORRECTION = 5
    BONUS = 6
    COMMISSION = 7
    COMMISSION_DAILY = 8
    COMMISSION_MONTHLY = 9
    COMMISSION_AGENT_DAILY = 10
    COMMISSION_AGENT_MONTHLY = 11
    INTEREST = 12
    BUY_CANCELED = 13
    SELL_CANCELED = 14


class OrderFilling(IntEnum):
    """MT5 OrderFilling constants."""

    FOK = 0
    IOC = 1
    RETURN = 2
    BOC = 3


class OrderReason(IntEnum):
    """MT5 OrderReason constants."""

    CLIENT = 0
    MOBILE = 1
    WEB = 2
    EXPERT = 3
    SL = 4
    TP = 5
    SO = 6


class OrderState(IntEnum):
    """MT5 OrderState constants."""

    STARTED = 0
    PLACED = 1
    CANCELED = 2
    PARTIAL = 3
    FILLED = 4
    REJECTED = 5
    EXPIRED = 6
    REQUEST_ADD = 7
    REQUEST_MODIFY = 8
    REQUEST_CANCEL = 9


class OrderTime(IntEnum):
    """MT5 OrderTime constants."""

    GTC = 0
    DAY = 1
    SPECIFIED = 2
    SPECIFIED_DAY = 3


class OrderType(IntEnum):
    """MT5 OrderType constants."""

    BUY = 0
    SELL = 1
    BUY_LIMIT = 2
    SELL_LIMIT = 3
    BUY_STOP = 4
    SELL_STOP = 5
    BUY_STOP_LIMIT = 6
    SELL_STOP_LIMIT = 7
    CLOSE_BY = 8


class PositionReason(IntEnum):
    """MT5 PositionReason constants."""

    CLIENT = 0
    MOBILE = 1
    WEB = 2
    EXPERT = 3


class PositionType(IntEnum):
    """MT5 PositionType constants."""

    BUY = 0
    SELL = 1


class SymbolCalcMode(IntEnum):
    """MT5 SymbolCalcMode constants."""

    FOREX = 0
    FUTURES = 1
    CFD = 2
    CFDINDEX = 3
    CFDLEVERAGE = 4
    FOREX_NO_LEVERAGE = 5
    EXCH_STOCKS = 32
    EXCH_FUTURES = 33
    EXCH_OPTIONS = 34
    EXCH_OPTIONS_MARGIN = 36
    EXCH_BONDS = 37
    EXCH_STOCKS_MOEX = 38
    EXCH_BONDS_MOEX = 39
    SERV_COLLATERAL = 64


class SymbolChartMode(IntEnum):
    """MT5 SymbolChartMode constants."""

    BID = 0
    LAST = 1


class SymbolOptionMode(IntEnum):
    """MT5 SymbolOptionMode constants."""

    EUROPEAN = 0
    AMERICAN = 1


class SymbolOptionRight(IntEnum):
    """MT5 SymbolOptionRight constants."""

    CALL = 0
    PUT = 1


class SymbolSwapMode(IntEnum):
    """MT5 SymbolSwapMode constants."""

    DISABLED = 0
    POINTS = 1
    CURRENCY_SYMBOL = 2
    CURRENCY_MARGIN = 3
    CURRENCY_DEPOSIT = 4
    INTEREST_CURRENT = 5
    INTEREST_OPEN = 6
    REOPEN_CURRENT = 7
    REOPEN_BID = 8


class SymbolTradeExecution(IntEnum):
    """MT5 SymbolTradeExecution constants."""

    REQUEST = 0
    INSTANT = 1
    MARKET = 2
    EXCHANGE = 3


class SymbolTradeMode(IntEnum):
    """MT5 SymbolTradeMode constants."""

    DISABLED = 0
    LONGONLY = 1
    SHORTONLY = 2
    CLOSEONLY = 3
    FULL = 4


class TickFlag(IntEnum):
    """MT5 TickFlag constants."""

    BID = 2
    ASK = 4
    LAST = 8
    VOLUME = 16
    BUY = 32
    SELL = 64


class TimeFrame(IntEnum):
    """MT5 TimeFrame constants."""

    M1 = 1
    M2 = 2
    M3 = 3
    M4 = 4
    M5 = 5
    M6 = 6
    M10 = 10
    M12 = 12
    M15 = 15
    M20 = 20
    M30 = 30
    H1 = 16385
    H2 = 16386
    H3 = 16387
    H4 = 16388
    H6 = 16390
    H8 = 16392
    H12 = 16396
    D1 = 16408
    W1 = 32769
    MN1 = 49153


class TradeAction(IntEnum):
    """MT5 TradeAction constants."""

    DEAL = 1
    PENDING = 5
    SLTP = 6
    MODIFY = 7
    REMOVE = 8
    CLOSE_BY = 10


class TradeRetcode(IntEnum):
    """MT5 TradeRetcode constants."""

    REQUOTE = 10004
    REJECT = 10006
    CANCEL = 10007
    PLACED = 10008
    DONE = 10009
    DONE_PARTIAL = 10010
    ERROR = 10011
    TIMEOUT = 10012
    INVALID = 10013
    INVALID_VOLUME = 10014
    INVALID_PRICE = 10015
    INVALID_STOPS = 10016
    TRADE_DISABLED = 10017
    MARKET_CLOSED = 10018
    NO_MONEY = 10019
    PRICE_CHANGED = 10020
    PRICE_OFF = 10021
    INVALID_EXPIRATION = 10022
    ORDER_CHANGED = 10023
    TOO_MANY_REQUESTS = 10024
    NO_CHANGES = 10025
    SERVER_DISABLES_AT = 10026
    CLIENT_DISABLES_AT = 10027
    LOCKED = 10028
    FROZEN = 10029
    INVALID_FILL = 10030
    CONNECTION = 10031
    ONLY_REAL = 10032
    LIMIT_ORDERS = 10033
    LIMIT_VOLUME = 10034
    INVALID_ORDER = 10035
    POSITION_CLOSED = 10036
    INVALID_CLOSE_VOLUME = 10038
    CLOSE_ORDER_EXIST = 10039
    LIMIT_POSITIONS = 10040
    REJECT_CANCEL = 10041
    LONG_ONLY = 10042
    SHORT_ONLY = 10043
    CLOSE_ONLY = 10044
    FIFO_CLOSE = 10045
