# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

if __package__:
    from . import mt5_pb2 as mt5__pb2
else:
    import mt5_pb2 as mt5__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in mt5_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MT5ServiceStub(object):
    """=============================================================================
    MT5 Service Definition
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
            "/mt5.MT5Service/HealthCheck",
            request_serializer=mt5__pb2.Empty.SerializeToString,
            response_deserializer=mt5__pb2.HealthStatus.FromString,
            _registered_method=True,
        )
        self.Initialize = channel.unary_unary(
            "/mt5.MT5Service/Initialize",
            request_serializer=mt5__pb2.InitRequest.SerializeToString,
            response_deserializer=mt5__pb2.BoolResponse.FromString,
            _registered_method=True,
        )
        self.Login = channel.unary_unary(
            "/mt5.MT5Service/Login",
            request_serializer=mt5__pb2.LoginRequest.SerializeToString,
            response_deserializer=mt5__pb2.BoolResponse.FromString,
            _registered_method=True,
        )
        self.Shutdown = channel.unary_unary(
            "/mt5.MT5Service/Shutdown",
            request_serializer=mt5__pb2.Empty.SerializeToString,
            response_deserializer=mt5__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.Version = channel.unary_unary(
            "/mt5.MT5Service/Version",
            request_serializer=mt5__pb2.Empty.SerializeToString,
            response_deserializer=mt5__pb2.MT5Version.FromString,
            _registered_method=True,
        )
        self.LastError = channel.unary_unary(
            "/mt5.MT5Service/LastError",
            request_serializer=mt5__pb2.Empty.SerializeToString,
            response_deserializer=mt5__pb2.ErrorInfo.FromString,
            _registered_method=True,
        )
        self.GetConstants = channel.unary_unary(
            "/mt5.MT5Service/GetConstants",
            request_serializer=mt5__pb2.Empty.SerializeToString,
            response_deserializer=mt5__pb2.Constants.FromString,
            _registered_method=True,
        )
        self.GetMethods = channel.unary_unary(
            "/mt5.MT5Service/GetMethods",
            request_serializer=mt5__pb2.Empty.SerializeToString,
            response_deserializer=mt5__pb2.MethodsResponse.FromString,
            _registered_method=True,
        )
        self.GetModels = channel.unary_unary(
            "/mt5.MT5Service/GetModels",
            request_serializer=mt5__pb2.Empty.SerializeToString,
            response_deserializer=mt5__pb2.ModelsResponse.FromString,
            _registered_method=True,
        )
        self.TerminalInfo = channel.unary_unary(
            "/mt5.MT5Service/TerminalInfo",
            request_serializer=mt5__pb2.Empty.SerializeToString,
            response_deserializer=mt5__pb2.DictData.FromString,
            _registered_method=True,
        )
        self.AccountInfo = channel.unary_unary(
            "/mt5.MT5Service/AccountInfo",
            request_serializer=mt5__pb2.Empty.SerializeToString,
            response_deserializer=mt5__pb2.DictData.FromString,
            _registered_method=True,
        )
        self.SymbolsTotal = channel.unary_unary(
            "/mt5.MT5Service/SymbolsTotal",
            request_serializer=mt5__pb2.Empty.SerializeToString,
            response_deserializer=mt5__pb2.IntResponse.FromString,
            _registered_method=True,
        )
        self.SymbolsGet = channel.unary_unary(
            "/mt5.MT5Service/SymbolsGet",
            request_serializer=mt5__pb2.SymbolsRequest.SerializeToString,
            response_deserializer=mt5__pb2.SymbolsResponse.FromString,
            _registered_method=True,
        )
        self.SymbolInfo = channel.unary_unary(
            "/mt5.MT5Service/SymbolInfo",
            request_serializer=mt5__pb2.SymbolRequest.SerializeToString,
            response_deserializer=mt5__pb2.DictData.FromString,
            _registered_method=True,
        )
        self.SymbolInfoTick = channel.unary_unary(
            "/mt5.MT5Service/SymbolInfoTick",
            request_serializer=mt5__pb2.SymbolRequest.SerializeToString,
            response_deserializer=mt5__pb2.DictData.FromString,
            _registered_method=True,
        )
        self.SymbolSelect = channel.unary_unary(
            "/mt5.MT5Service/SymbolSelect",
            request_serializer=mt5__pb2.SymbolSelectRequest.SerializeToString,
            response_deserializer=mt5__pb2.BoolResponse.FromString,
            _registered_method=True,
        )
        self.CopyRatesFrom = channel.unary_unary(
            "/mt5.MT5Service/CopyRatesFrom",
            request_serializer=mt5__pb2.CopyRatesRequest.SerializeToString,
            response_deserializer=mt5__pb2.NumpyArray.FromString,
            _registered_method=True,
        )
        self.CopyRatesFromPos = channel.unary_unary(
            "/mt5.MT5Service/CopyRatesFromPos",
            request_serializer=mt5__pb2.CopyRatesPosRequest.SerializeToString,
            response_deserializer=mt5__pb2.NumpyArray.FromString,
            _registered_method=True,
        )
        self.CopyRatesRange = channel.unary_unary(
            "/mt5.MT5Service/CopyRatesRange",
            request_serializer=mt5__pb2.CopyRatesRangeRequest.SerializeToString,
            response_deserializer=mt5__pb2.NumpyArray.FromString,
            _registered_method=True,
        )
        self.CopyTicksFrom = channel.unary_unary(
            "/mt5.MT5Service/CopyTicksFrom",
            request_serializer=mt5__pb2.CopyTicksRequest.SerializeToString,
            response_deserializer=mt5__pb2.NumpyArray.FromString,
            _registered_method=True,
        )
        self.CopyTicksRange = channel.unary_unary(
            "/mt5.MT5Service/CopyTicksRange",
            request_serializer=mt5__pb2.CopyTicksRangeRequest.SerializeToString,
            response_deserializer=mt5__pb2.NumpyArray.FromString,
            _registered_method=True,
        )
        self.OrderCalcMargin = channel.unary_unary(
            "/mt5.MT5Service/OrderCalcMargin",
            request_serializer=mt5__pb2.MarginRequest.SerializeToString,
            response_deserializer=mt5__pb2.FloatResponse.FromString,
            _registered_method=True,
        )
        self.OrderCalcProfit = channel.unary_unary(
            "/mt5.MT5Service/OrderCalcProfit",
            request_serializer=mt5__pb2.ProfitRequest.SerializeToString,
            response_deserializer=mt5__pb2.FloatResponse.FromString,
            _registered_method=True,
        )
        self.OrderCheck = channel.unary_unary(
            "/mt5.MT5Service/OrderCheck",
            request_serializer=mt5__pb2.OrderRequest.SerializeToString,
            response_deserializer=mt5__pb2.DictData.FromString,
            _registered_method=True,
        )
        self.OrderSend = channel.unary_unary(
            "/mt5.MT5Service/OrderSend",
            request_serializer=mt5__pb2.OrderRequest.SerializeToString,
            response_deserializer=mt5__pb2.DictData.FromString,
            _registered_method=True,
        )
        self.PositionsTotal = channel.unary_unary(
            "/mt5.MT5Service/PositionsTotal",
            request_serializer=mt5__pb2.Empty.SerializeToString,
            response_deserializer=mt5__pb2.IntResponse.FromString,
            _registered_method=True,
        )
        self.PositionsGet = channel.unary_unary(
            "/mt5.MT5Service/PositionsGet",
            request_serializer=mt5__pb2.PositionsRequest.SerializeToString,
            response_deserializer=mt5__pb2.DictList.FromString,
            _registered_method=True,
        )
        self.OrdersTotal = channel.unary_unary(
            "/mt5.MT5Service/OrdersTotal",
            request_serializer=mt5__pb2.Empty.SerializeToString,
            response_deserializer=mt5__pb2.IntResponse.FromString,
            _registered_method=True,
        )
        self.OrdersGet = channel.unary_unary(
            "/mt5.MT5Service/OrdersGet",
            request_serializer=mt5__pb2.OrdersRequest.SerializeToString,
            response_deserializer=mt5__pb2.DictList.FromString,
            _registered_method=True,
        )
        self.HistoryOrdersTotal = channel.unary_unary(
            "/mt5.MT5Service/HistoryOrdersTotal",
            request_serializer=mt5__pb2.HistoryRequest.SerializeToString,
            response_deserializer=mt5__pb2.IntResponse.FromString,
            _registered_method=True,
        )
        self.HistoryOrdersGet = channel.unary_unary(
            "/mt5.MT5Service/HistoryOrdersGet",
            request_serializer=mt5__pb2.HistoryRequest.SerializeToString,
            response_deserializer=mt5__pb2.DictList.FromString,
            _registered_method=True,
        )
        self.HistoryDealsTotal = channel.unary_unary(
            "/mt5.MT5Service/HistoryDealsTotal",
            request_serializer=mt5__pb2.HistoryRequest.SerializeToString,
            response_deserializer=mt5__pb2.IntResponse.FromString,
            _registered_method=True,
        )
        self.HistoryDealsGet = channel.unary_unary(
            "/mt5.MT5Service/HistoryDealsGet",
            request_serializer=mt5__pb2.HistoryRequest.SerializeToString,
            response_deserializer=mt5__pb2.DictList.FromString,
            _registered_method=True,
        )
        self.MarketBookAdd = channel.unary_unary(
            "/mt5.MT5Service/MarketBookAdd",
            request_serializer=mt5__pb2.SymbolRequest.SerializeToString,
            response_deserializer=mt5__pb2.BoolResponse.FromString,
            _registered_method=True,
        )
        self.MarketBookGet = channel.unary_unary(
            "/mt5.MT5Service/MarketBookGet",
            request_serializer=mt5__pb2.SymbolRequest.SerializeToString,
            response_deserializer=mt5__pb2.DictList.FromString,
            _registered_method=True,
        )
        self.MarketBookRelease = channel.unary_unary(
            "/mt5.MT5Service/MarketBookRelease",
            request_serializer=mt5__pb2.SymbolRequest.SerializeToString,
            response_deserializer=mt5__pb2.BoolResponse.FromString,
            _registered_method=True,
        )


class MT5ServiceServicer(object):
    """=============================================================================
    MT5 Service Definition
    =============================================================================

    """

    def HealthCheck(self, request, context):
        """Terminal operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Initialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LastError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetConstants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMethods(self, request, context):
        """Introspection (for protocol validation)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TerminalInfo(self, request, context):
        """Account/Terminal info"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AccountInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SymbolsTotal(self, request, context):
        """Symbol operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SymbolsGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SymbolInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SymbolInfoTick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SymbolSelect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CopyRatesFrom(self, request, context):
        """Market data - returns numpy arrays as bytes"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CopyRatesFromPos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CopyRatesRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CopyTicksFrom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CopyTicksRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def OrderCalcMargin(self, request, context):
        """Trading operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def OrderCalcProfit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def OrderCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def OrderSend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PositionsTotal(self, request, context):
        """Position operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PositionsGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def OrdersTotal(self, request, context):
        """Order operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def OrdersGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HistoryOrdersTotal(self, request, context):
        """History operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HistoryOrdersGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HistoryDealsTotal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HistoryDealsGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MarketBookAdd(self, request, context):
        """Market Depth (DOM) operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MarketBookGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MarketBookRelease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MT5ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=mt5__pb2.Empty.FromString,
            response_serializer=mt5__pb2.HealthStatus.SerializeToString,
        ),
        "Initialize": grpc.unary_unary_rpc_method_handler(
            servicer.Initialize,
            request_deserializer=mt5__pb2.InitRequest.FromString,
            response_serializer=mt5__pb2.BoolResponse.SerializeToString,
        ),
        "Login": grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=mt5__pb2.LoginRequest.FromString,
            response_serializer=mt5__pb2.BoolResponse.SerializeToString,
        ),
        "Shutdown": grpc.unary_unary_rpc_method_handler(
            servicer.Shutdown,
            request_deserializer=mt5__pb2.Empty.FromString,
            response_serializer=mt5__pb2.Empty.SerializeToString,
        ),
        "Version": grpc.unary_unary_rpc_method_handler(
            servicer.Version,
            request_deserializer=mt5__pb2.Empty.FromString,
            response_serializer=mt5__pb2.MT5Version.SerializeToString,
        ),
        "LastError": grpc.unary_unary_rpc_method_handler(
            servicer.LastError,
            request_deserializer=mt5__pb2.Empty.FromString,
            response_serializer=mt5__pb2.ErrorInfo.SerializeToString,
        ),
        "GetConstants": grpc.unary_unary_rpc_method_handler(
            servicer.GetConstants,
            request_deserializer=mt5__pb2.Empty.FromString,
            response_serializer=mt5__pb2.Constants.SerializeToString,
        ),
        "GetMethods": grpc.unary_unary_rpc_method_handler(
            servicer.GetMethods,
            request_deserializer=mt5__pb2.Empty.FromString,
            response_serializer=mt5__pb2.MethodsResponse.SerializeToString,
        ),
        "GetModels": grpc.unary_unary_rpc_method_handler(
            servicer.GetModels,
            request_deserializer=mt5__pb2.Empty.FromString,
            response_serializer=mt5__pb2.ModelsResponse.SerializeToString,
        ),
        "TerminalInfo": grpc.unary_unary_rpc_method_handler(
            servicer.TerminalInfo,
            request_deserializer=mt5__pb2.Empty.FromString,
            response_serializer=mt5__pb2.DictData.SerializeToString,
        ),
        "AccountInfo": grpc.unary_unary_rpc_method_handler(
            servicer.AccountInfo,
            request_deserializer=mt5__pb2.Empty.FromString,
            response_serializer=mt5__pb2.DictData.SerializeToString,
        ),
        "SymbolsTotal": grpc.unary_unary_rpc_method_handler(
            servicer.SymbolsTotal,
            request_deserializer=mt5__pb2.Empty.FromString,
            response_serializer=mt5__pb2.IntResponse.SerializeToString,
        ),
        "SymbolsGet": grpc.unary_unary_rpc_method_handler(
            servicer.SymbolsGet,
            request_deserializer=mt5__pb2.SymbolsRequest.FromString,
            response_serializer=mt5__pb2.SymbolsResponse.SerializeToString,
        ),
        "SymbolInfo": grpc.unary_unary_rpc_method_handler(
            servicer.SymbolInfo,
            request_deserializer=mt5__pb2.SymbolRequest.FromString,
            response_serializer=mt5__pb2.DictData.SerializeToString,
        ),
        "SymbolInfoTick": grpc.unary_unary_rpc_method_handler(
            servicer.SymbolInfoTick,
            request_deserializer=mt5__pb2.SymbolRequest.FromString,
            response_serializer=mt5__pb2.DictData.SerializeToString,
        ),
        "SymbolSelect": grpc.unary_unary_rpc_method_handler(
            servicer.SymbolSelect,
            request_deserializer=mt5__pb2.SymbolSelectRequest.FromString,
            response_serializer=mt5__pb2.BoolResponse.SerializeToString,
        ),
        "CopyRatesFrom": grpc.unary_unary_rpc_method_handler(
            servicer.CopyRatesFrom,
            request_deserializer=mt5__pb2.CopyRatesRequest.FromString,
            response_serializer=mt5__pb2.NumpyArray.SerializeToString,
        ),
        "CopyRatesFromPos": grpc.unary_unary_rpc_method_handler(
            servicer.CopyRatesFromPos,
            request_deserializer=mt5__pb2.CopyRatesPosRequest.FromString,
            response_serializer=mt5__pb2.NumpyArray.SerializeToString,
        ),
        "CopyRatesRange": grpc.unary_unary_rpc_method_handler(
            servicer.CopyRatesRange,
            request_deserializer=mt5__pb2.CopyRatesRangeRequest.FromString,
            response_serializer=mt5__pb2.NumpyArray.SerializeToString,
        ),
        "CopyTicksFrom": grpc.unary_unary_rpc_method_handler(
            servicer.CopyTicksFrom,
            request_deserializer=mt5__pb2.CopyTicksRequest.FromString,
            response_serializer=mt5__pb2.NumpyArray.SerializeToString,
        ),
        "CopyTicksRange": grpc.unary_unary_rpc_method_handler(
            servicer.CopyTicksRange,
            request_deserializer=mt5__pb2.CopyTicksRangeRequest.FromString,
            response_serializer=mt5__pb2.NumpyArray.SerializeToString,
        ),
        "OrderCalcMargin": grpc.unary_unary_rpc_method_handler(
            servicer.OrderCalcMargin,
            request_deserializer=mt5__pb2.MarginRequest.FromString,
            response_serializer=mt5__pb2.FloatResponse.SerializeToString,
        ),
        "OrderCalcProfit": grpc.unary_unary_rpc_method_handler(
            servicer.OrderCalcProfit,
            request_deserializer=mt5__pb2.ProfitRequest.FromString,
            response_serializer=mt5__pb2.FloatResponse.SerializeToString,
        ),
        "OrderCheck": grpc.unary_unary_rpc_method_handler(
            servicer.OrderCheck,
            request_deserializer=mt5__pb2.OrderRequest.FromString,
            response_serializer=mt5__pb2.DictData.SerializeToString,
        ),
        "OrderSend": grpc.unary_unary_rpc_method_handler(
            servicer.OrderSend,
            request_deserializer=mt5__pb2.OrderRequest.FromString,
            response_serializer=mt5__pb2.DictData.SerializeToString,
        ),
        "PositionsTotal": grpc.unary_unary_rpc_method_handler(
            servicer.PositionsTotal,
            request_deserializer=mt5__pb2.Empty.FromString,
            response_serializer=mt5__pb2.IntResponse.SerializeToString,
        ),
        "PositionsGet": grpc.unary_unary_rpc_method_handler(
            servicer.PositionsGet,
            request_deserializer=mt5__pb2.PositionsRequest.FromString,
            response_serializer=mt5__pb2.DictList.SerializeToString,
        ),
        "OrdersTotal": grpc.unary_unary_rpc_method_handler(
            servicer.OrdersTotal,
            request_deserializer=mt5__pb2.Empty.FromString,
            response_serializer=mt5__pb2.IntResponse.SerializeToString,
        ),
        "OrdersGet": grpc.unary_unary_rpc_method_handler(
            servicer.OrdersGet,
            request_deserializer=mt5__pb2.OrdersRequest.FromString,
            response_serializer=mt5__pb2.DictList.SerializeToString,
        ),
        "HistoryOrdersTotal": grpc.unary_unary_rpc_method_handler(
            servicer.HistoryOrdersTotal,
            request_deserializer=mt5__pb2.HistoryRequest.FromString,
            response_serializer=mt5__pb2.IntResponse.SerializeToString,
        ),
        "HistoryOrdersGet": grpc.unary_unary_rpc_method_handler(
            servicer.HistoryOrdersGet,
            request_deserializer=mt5__pb2.HistoryRequest.FromString,
            response_serializer=mt5__pb2.DictList.SerializeToString,
        ),
        "HistoryDealsTotal": grpc.unary_unary_rpc_method_handler(
            servicer.HistoryDealsTotal,
            request_deserializer=mt5__pb2.HistoryRequest.FromString,
            response_serializer=mt5__pb2.IntResponse.SerializeToString,
        ),
        "HistoryDealsGet": grpc.unary_unary_rpc_method_handler(
            servicer.HistoryDealsGet,
            request_deserializer=mt5__pb2.HistoryRequest.FromString,
            response_serializer=mt5__pb2.DictList.SerializeToString,
        ),
        "MarketBookAdd": grpc.unary_unary_rpc_method_handler(
            servicer.MarketBookAdd,
            request_deserializer=mt5__pb2.SymbolRequest.FromString,
            response_serializer=mt5__pb2.BoolResponse.SerializeToString,
        ),
        "MarketBookGet": grpc.unary_unary_rpc_method_handler(
            servicer.MarketBookGet,
            request_deserializer=mt5__pb2.SymbolRequest.FromString,
            response_serializer=mt5__pb2.DictList.SerializeToString,
        ),
        "MarketBookRelease": grpc.unary_unary_rpc_method_handler(
            servicer.MarketBookRelease,
            request_deserializer=mt5__pb2.SymbolRequest.FromString,
            response_serializer=mt5__pb2.BoolResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "mt5.MT5Service", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("mt5.MT5Service", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MT5Service(object):
    """=============================================================================
    MT5 Service Definition
    =============================================================================

    """

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/HealthCheck",
            mt5__pb2.Empty.SerializeToString,
            mt5__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Initialize(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/Initialize",
            mt5__pb2.InitRequest.SerializeToString,
            mt5__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Login(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/Login",
            mt5__pb2.LoginRequest.SerializeToString,
            mt5__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Shutdown(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/Shutdown",
            mt5__pb2.Empty.SerializeToString,
            mt5__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Version(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/Version",
            mt5__pb2.Empty.SerializeToString,
            mt5__pb2.MT5Version.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def LastError(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/LastError",
            mt5__pb2.Empty.SerializeToString,
            mt5__pb2.ErrorInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetConstants(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/GetConstants",
            mt5__pb2.Empty.SerializeToString,
            mt5__pb2.Constants.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMethods(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/GetMethods",
            mt5__pb2.Empty.SerializeToString,
            mt5__pb2.MethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetModels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/GetModels",
            mt5__pb2.Empty.SerializeToString,
            mt5__pb2.ModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TerminalInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/TerminalInfo",
            mt5__pb2.Empty.SerializeToString,
            mt5__pb2.DictData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AccountInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/AccountInfo",
            mt5__pb2.Empty.SerializeToString,
            mt5__pb2.DictData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SymbolsTotal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/SymbolsTotal",
            mt5__pb2.Empty.SerializeToString,
            mt5__pb2.IntResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SymbolsGet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/SymbolsGet",
            mt5__pb2.SymbolsRequest.SerializeToString,
            mt5__pb2.SymbolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SymbolInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/SymbolInfo",
            mt5__pb2.SymbolRequest.SerializeToString,
            mt5__pb2.DictData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SymbolInfoTick(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/SymbolInfoTick",
            mt5__pb2.SymbolRequest.SerializeToString,
            mt5__pb2.DictData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SymbolSelect(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/SymbolSelect",
            mt5__pb2.SymbolSelectRequest.SerializeToString,
            mt5__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CopyRatesFrom(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/CopyRatesFrom",
            mt5__pb2.CopyRatesRequest.SerializeToString,
            mt5__pb2.NumpyArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CopyRatesFromPos(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/CopyRatesFromPos",
            mt5__pb2.CopyRatesPosRequest.SerializeToString,
            mt5__pb2.NumpyArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CopyRatesRange(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/CopyRatesRange",
            mt5__pb2.CopyRatesRangeRequest.SerializeToString,
            mt5__pb2.NumpyArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CopyTicksFrom(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/CopyTicksFrom",
            mt5__pb2.CopyTicksRequest.SerializeToString,
            mt5__pb2.NumpyArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CopyTicksRange(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/CopyTicksRange",
            mt5__pb2.CopyTicksRangeRequest.SerializeToString,
            mt5__pb2.NumpyArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def OrderCalcMargin(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/OrderCalcMargin",
            mt5__pb2.MarginRequest.SerializeToString,
            mt5__pb2.FloatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def OrderCalcProfit(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/OrderCalcProfit",
            mt5__pb2.ProfitRequest.SerializeToString,
            mt5__pb2.FloatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def OrderCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/OrderCheck",
            mt5__pb2.OrderRequest.SerializeToString,
            mt5__pb2.DictData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def OrderSend(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/OrderSend",
            mt5__pb2.OrderRequest.SerializeToString,
            mt5__pb2.DictData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PositionsTotal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/PositionsTotal",
            mt5__pb2.Empty.SerializeToString,
            mt5__pb2.IntResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PositionsGet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/PositionsGet",
            mt5__pb2.PositionsRequest.SerializeToString,
            mt5__pb2.DictList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def OrdersTotal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/OrdersTotal",
            mt5__pb2.Empty.SerializeToString,
            mt5__pb2.IntResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def OrdersGet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/OrdersGet",
            mt5__pb2.OrdersRequest.SerializeToString,
            mt5__pb2.DictList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HistoryOrdersTotal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/HistoryOrdersTotal",
            mt5__pb2.HistoryRequest.SerializeToString,
            mt5__pb2.IntResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HistoryOrdersGet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/HistoryOrdersGet",
            mt5__pb2.HistoryRequest.SerializeToString,
            mt5__pb2.DictList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HistoryDealsTotal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/HistoryDealsTotal",
            mt5__pb2.HistoryRequest.SerializeToString,
            mt5__pb2.IntResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HistoryDealsGet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/HistoryDealsGet",
            mt5__pb2.HistoryRequest.SerializeToString,
            mt5__pb2.DictList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MarketBookAdd(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/MarketBookAdd",
            mt5__pb2.SymbolRequest.SerializeToString,
            mt5__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MarketBookGet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/MarketBookGet",
            mt5__pb2.SymbolRequest.SerializeToString,
            mt5__pb2.DictList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MarketBookRelease(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mt5.MT5Service/MarketBookRelease",
            mt5__pb2.SymbolRequest.SerializeToString,
            mt5__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
